FROM alpine
ARG USERNAME=app
ARG USER_UID=10000
ARG USER_GID=$USER_UID
RUN addgroup -g $USER_GID $USERNAME && adduser -u $USER_UID -G $USERNAME -D $USERNAME
USER $USERNAME
WORKDIR /app
ARG TARGETOS
ARG TARGETARCH
COPY --chown=$USERNAME:$USERNAME out/$TARGETOS-$TARGETARCH/* .
CMD ["./slimlink"]
EXPOSE 44558
