import js from "@eslint/js";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig([
	globalIgnores(["dist"]),
	reactHooks.configs.flat.recommended,
	reactRefresh.configs.vite,
	react.configs.flat.recommended,
	js.configs.recommended,
	{
		settings: {
			react: {
				version: "detect",
			},
		},
		rules: {
			"@next/next/no-img-element": "off",
			"array-bracket-spacing": ["error", "never"],
			"array-element-newline": ["error", "consistent"],
			"arrow-body-style": ["error", "as-needed"],
			"arrow-parens": "error",
			"arrow-spacing": "error",
			"block-spacing": "error",
			"brace-style": ["error", "1tbs"],
			"comma-dangle": ["warn", "always-multiline"],
			"comma-spacing": [
				"error",
				{
					after: true,
					before: false,
				},
			],
			"comma-style": ["error", "last"],
			"computed-property-spacing": "error",
			curly: ["error", "all"],
			"default-case": "error",
			"dot-location": ["error", "property"],
			"eol-last": "error",
			eqeqeq: "error",
			"func-names": "error",
			"func-style": ["error", "declaration"],
			// "import/first": "error",
			// "import/no-anonymous-default-export": "error",
			// "import/no-dynamic-require": "error",
			// "import/no-mutable-exports": "error",
			// "import/no-unused-modules": "error",
			// "import/prefer-default-export": "off",
			indent: [
				"error",
				"tab",
				{
					ignoredNodes: ["TemplateLiteral"],
					SwitchCase: 1,
				},
			],
			"jsx-a11y/anchor-is-valid": "off",
			"jsx-a11y/no-autofocus": "off",
			"linebreak-style": ["warn", "unix"],
			"lines-between-class-members": [
				"error",
				"always",
				{
					exceptAfterSingleLine: true,
				},
			],
			"multiline-comment-style": ["error", "separate-lines"],
			"multiline-ternary": "off", // Handled by Prettier
			"new-parens": "error",
			"no-alert": "warn",
			"no-array-constructor": "error",
			"no-await-in-loop": "error",
			"no-bitwise": "error",
			"no-confusing-arrow": "error",
			"no-console": "warn",
			"no-duplicate-imports": "warn",
			"no-else-return": "error",
			"no-empty": [
				"warn",
				{
					allowEmptyCatch: true,
				},
			],
			"no-fallthrough": "error",
			"no-invalid-this": "error",
			"no-lonely-if": "error",
			"no-multi-spaces": "error",
			"no-multiple-empty-lines": "error",
			"no-self-compare": "error",
			"no-template-curly-in-string": "error",
			"no-trailing-spaces": "error",
			"no-undef-init": "error",
			"no-undefined": "off",
			"no-unreachable-loop": "error",
			"no-unused-expressions": "error",
			"no-unused-vars": [
				"warn",
				{
					args: "all",
					argsIgnorePattern: "^_",
					caughtErrors: "all",
					vars: "all",
				},
			],
			"no-use-before-define": "off",
			"no-useless-catch": "error",
			"no-useless-computed-key": "error",
			"no-useless-concat": "error",
			"no-useless-constructor": "error",
			"no-useless-rename": "error",
			"no-useless-return": "error",
			"no-whitespace-before-property": "error",
			"object-curly-newline": [
				"error",
				{
					consistent: true,
					multiline: true,
				},
			],
			"object-curly-spacing": ["error", "always"],
			"object-property-newline": [
				"error",
				{
					allowAllPropertiesOnSameLine: true,
				},
			],
			"one-var-declaration-per-line": "error",
			"operator-assignment": "error",
			"operator-linebreak": "off", // Handled by Prettier
			"prefer-arrow-callback": "error",
			"prefer-const": "error",
			"prefer-destructuring": [
				"error",
				{
					AssignmentExpression: {
						array: false,
						object: false,
					},

					VariableDeclarator: {
						array: false,
						object: true,
					},
				},
			],
			"prefer-object-spread": "error",
			"prefer-spread": "error",
			"prefer-template": "error",
			quotes: ["error", "double"],
			radix: ["error", "as-needed"],
			"react-hooks/exhaustive-deps": [
				"error",
				{
					additionalHooks: "useUpdateEffect",
				},
			],
			"react-hooks/rules-of-hooks": "error",
			"react/boolean-prop-naming": "error",
			"react/display-name": "off",
			"react/function-component-definition": "error",
			"react/jsx-boolean-value": "error",
			"react/jsx-child-element-spacing": "error",
			"react/jsx-closing-bracket-location": "error",
			"react/jsx-curly-brace-presence": "error",
			"react/jsx-equals-spacing": ["error", "never"],
			"react/jsx-filename-extension": [
				"error",
				{
					extensions: [".jsx", ".tsx"],
				},
			],

			"react/jsx-handler-names": "error",
			"react/jsx-no-useless-fragment": "error",
			"react/jsx-pascal-case": "error",
			"react/jsx-props-no-multi-spaces": "error",
			"react/jsx-sort-props": "warn",
			"react/jsx-tag-spacing": "error",
			"react/jsx-uses-react": "off",
			"react/no-access-state-in-setstate": "error",
			"react/no-adjacent-inline-elements": "error",
			"react/no-danger": "warn",
			"react/no-did-mount-set-state": "error",
			"react/no-did-update-set-state": "error",
			"react/no-this-in-sfc": "error",
			"react/no-typos": "error",
			"react/no-unsafe": "error",
			"react/prefer-stateless-function": "error",
			"react/prop-types": "off",
			"react/react-in-jsx-scope": "off",
			"react/sort-comp": "warn",
			"react/sort-default-props": "warn",
			"react/sort-prop-types": "warn",
			"require-await": "error",
			semi: ["error", "always"],
			"semi-spacing": "error",
			"sort-imports": [
				"warn",
				{
					ignoreCase: true,
					ignoreDeclarationSort: true,
				},
			],
			"space-before-blocks": "error",
			"space-before-function-paren": [
				"error",
				{
					anonymous: "never",
					asyncArrow: "always",
					named: "never",
				},
			],
			"space-in-parens": "error",
			"space-infix-ops": "error",
			"spaced-comment": [
				"error",
				"always",
				{
					markers: ["/"],
				},
			],
			"switch-colon-spacing": "error",
			"template-curly-spacing": "error",
			"template-tag-spacing": ["error", "never"],
			"wrap-regex": "error",
		},
	},
	{
		files: ["**/*.ts", "**/*.tsx"],
		extends: [tseslint.configs.recommendedTypeChecked, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
		languageOptions: {
			parserOptions: {
				project: "tsconfig.json",
				warnOnUnsupportedTypeScriptVersion: false,
			},
		},
		rules: {
			"@typescript-eslint/array-type": [
				"error",
				{
					default: "generic",
				},
			],
			"@typescript-eslint/ban-ts-comment": "warn",
			"@typescript-eslint/class-literal-property-style": "error",
			"@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
			"@typescript-eslint/consistent-type-assertions": "error",
			"@typescript-eslint/consistent-type-definitions": ["error", "interface"],
			"@typescript-eslint/explicit-function-return-type": "off",
			"@typescript-eslint/explicit-member-accessibility": "error",
			"@typescript-eslint/explicit-module-boundary-types": "off",
			// "@typescript-eslint/indent": [
			// 	"error",
			// 	"tab",
			// 	{
			// 		SwitchCase: 1,
			// 	},
			// ],
			"@typescript-eslint/method-signature-style": "error",
			"@typescript-eslint/no-array-constructor": "error",
			"@typescript-eslint/no-confusing-non-null-assertion": "error",
			"@typescript-eslint/no-explicit-any": "error",
			"@typescript-eslint/no-redeclare": "off",
			"@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
			"@typescript-eslint/no-unused-expressions": "error",
			"@typescript-eslint/no-unused-vars": [
				"warn",
				{
					args: "all",
					argsIgnorePattern: "^_",
					caughtErrors: "all",
					vars: "all",
				},
			],
			"@typescript-eslint/no-use-before-define": "off",
			"@typescript-eslint/no-useless-constructor": "error",
			"@typescript-eslint/prefer-for-of": "error",
			"@typescript-eslint/prefer-includes": "error",
			"@typescript-eslint/prefer-readonly": "error",
			indent: "off",
			"no-array-constructor": "off",
			"no-fallthrough": "off",
			"no-unused-expressions": "off",
			"no-unused-vars": "off",
			"no-useless-constructor": "off",
			"@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
		},
	},
]);
